name: Build Status

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Set up SFTP test environment
      run: |
        sudo apt-get update
        sudo apt-get install -y openssl openssh-server

        # Add host to /etc/hosts
        echo "127.0.0.1 sftp.server.example" | sudo tee -a /etc/hosts

        # Create test user and setup directories
        sudo adduser --disabled-password --gecos "SFTP Test" sftp_test
        echo "sftp_test:password" | sudo chpasswd

        # Setup SSH and SFTP directories
        sudo mkdir -p /home/sftp_test/.ssh/
        sudo mkdir -p /home/sftp_test/existing_upload_folder/
        sudo mkdir -p /home/sftp_test/non_empty_folder/subfolder
        sudo mkdir -p /var/ftp/sftp_test/
        sudo mkdir -p /home/sftp_test/download/sub_folder

        # Create test files
        sudo touch /home/sftp_test/non_empty_folder/old.txt
        sudo touch /home/sftp_test/non_empty_folder/subfolder/old.txt
        sudo touch /home/sftp_test/download/file_01.txt
        sudo touch /home/sftp_test/download/file_02.txt
        sudo touch /home/sftp_test/download/sub_folder/file_03.txt
        sudo touch /home/sftp_test/download/sub_folder/file_04.txt

        # Setup SSH configuration
        sudo cp -f assets/sshd_config /etc/ssh/
        sudo cp -f assets/authorized_keys /home/sftp_test/.ssh/

        # Set permissions
        sudo chown sftp_test:sftp_test /home/sftp_test/existing_upload_folder
        sudo chown -R sftp_test:sftp_test /home/sftp_test/non_empty_folder
        sudo chown sftp_test:sftp_test /var/ftp/sftp_test
        sudo chown -R sftp_test:sftp_test /home/sftp_test/download
        sudo chown -R sftp_test:sftp_test /home/sftp_test/.ssh
        # sudo chown -R sftp_test:sftp_test /home/sftp_test

        #sudo chmod 700 /home/sftp_test/.ssh
        #sudo chmod 600 /home/sftp_test/.ssh/authorized_keys   
        
        # Setup SSH for runner
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        chmod -R go= assets/keys
        ssh-keyscan -H sftp.server.example >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

        # Restart SSH service
        sudo service ssh restart

        # Debug info
        ls -la /home/sftp_test/.ssh/
        sudo cat /etc/ssh/sshd_config
    - name: Run tests
      run: bundle exec rake